
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To update this file, edit the 'backend.json' file in the 'docs' directory.
import { FirebaseOptions, initializeApp, getApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID"
};

function initializeFirebaseApp() {
  try {
    return getApp();
  } catch {
    return initializeApp(firebaseConfig);
  }
}

export const firebaseApp = initializeFirebaseApp();
