
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To update this file, edit the 'backend.json' file in the 'docs' directory.
import { FirebaseOptions, initializeApp, getApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDnLDEfWfMM0VDaZUzvjY1_gsO94Mh1TTA",
  authDomain: "studio-2441159653-157ae.firebaseapp.com",
  projectId: "studio-2441159653-157ae",
  storageBucket: "studio-2441159653-157ae.firebasestorage.app",
  messagingSenderId: "1067495317033",
  appId: "1:1067495317033:web:447d00461e0346e2228638"
};

function initializeFirebaseApp() {
  try {
    return getApp();
  } catch {
    return initializeApp(firebaseConfig);
  }
}

export const firebaseApp = initializeFirebaseApp();
